[package]
name = "http-server"
version = "0.1.0"
authors = ["jorbush"]
edition = "2021"

[dependencies]
flate2 = "1.0.30"

[dev-dependencies]
pretty_assertions = "1.3.0"                         # nicer looking assertions
